language: python

python:
    - '2.7'

install:
    - pip install robotframework

script:
    - pybot --pythonpath RobotDemo RobotDemo/keyword_driven.txt

after_success: 
    - ./update-gh-pages.sh

env:
    global:
        secure: JLe2lqncV4mh/Kb++T+qhO+6PTUovX3dGtcyYEONoXUG03MAOOMcRKPF4H1xoly4deiWr3zNYfT3pE2pobXaqP/8/YVaY09YJuShrS4Vou4xFEelcZJqX0g5p1IYfTGNRBghteDq53fdQWgOLmdcF/LSjsMslYZ1dKq2AHS66ds=
